apps/wallpapers_main/urls.py
from django.urls import path
from . import views

app_name = 'wallpapers_main'
urlpatterns = [
    path('load', views.load, name='load'),
    path('load/result', views.load_result, name='load_result'),

    path('sort', views.sort, name='sort'),
    path('category_take', views.category_take, name = 'category_take'),

    path('category/<str:category>', views.view_image, name = 'category'),
    path('category/<str:category>/<int:page>', views.view_image, name = 'category_page'),

    path('index/<str:image_name>', views.view_image_page, name = 'image_page'),

    path('error', views.error_redirect, name = 'error_redirect'),

    path('', views.view_image, name = 'recommend'),
]

wallpapers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wallpapers_main.urls')),
]

apps/utils/models.py
from django.db import models

# Create your models here.

apps/wallpapers_main/models.py
from django.db import models

class Category(models.Model):
    category_name = models.CharField('Категория', max_length = 30, unique=True)
    category_link_name = models.CharField('Название для ссылки', max_length=30, unique=True)

    def __str__(self):
        return self.category_name

class Images(models.Model):
    name = models.CharField('Имя картинки', max_length = 256, unique=True)
    categories = models.ManyToManyField(Category, blank=True)
    date = models.DateField('Дата загрузки', auto_now=True)

    # def get_last_added(amount_images):
    #     '''Возвращает последние добавленые картинки в количестве
    #      равном amount_images'''
    #     if not isinstance(amount_images, int):
    #         raise AttributeError('wrong type of amount_images')
    #     return Images.objects.order_by('-date')[:amount_images]

    def __str__(self):
        return self.name

class Source(models.Model):
    SIZES = [
    ('1280x720', 'HD'),
    ('1600x900', 'WXGA++'),
    ('1920x1080', 'Full HD'),
    ('2560×1440', 'Quad HD'),
    ]
    name = models.ForeignKey(Images, on_delete = models.CASCADE)
    size = models.CharField('Разрешение', choices=SIZES, max_length=30)
    source = models.URLField('Ссылка на источник')

    def __str__(self):
        return self.source

    # def get_last_added(size='1920x1080'):
    #     '''Возвращает последние добавленые картинки в количестве
    #      равном amount_images'''
    #     images = Images.objects.order_by('-date')
    #     return Source.objects.filter(name__in = images).filter(size=size)

apps/utils/views.py
from django.shortcuts import render

# Create your views here.

apps/wallpapers_main/views.py
from .models import Images, Source, Category
from utils.parser import Parser

from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError, OperationalError
from django.core.paginator import Paginator


def load(request): #Загружает страницу для выбора способа загрузки картинок
    sizes = tuple(named_size[0] for named_size in Source.SIZES)
    return render(request, "wallpapers_main\load.html", context = {'sizes':sizes} )

def load_result(request):  #Загружает страницу вывода результатов загрузки картинок( ) и вызывает функции для загрузки картинок
    load_select = request.POST.get('load_select')
    print(load_select)
    if load_select == 'parse_site':
        result = parse_site_and_download(url = request.POST.get('url'),
                                        duration = int(request.POST.get('duration')))
    elif load_select == 'upload_file':
        result = download_file()
    else:
        result = {'Error':'Неправильный запрос на загрузку'}
    return render(request, 'wallpapers_main\\result.html', context = {'result':result})


def view_image_page(request, image_name):
    try:
        image_sources = Source.objects.filter(name__name=image_name)
    except OperationalError:
        context = {'error_message':'Картинка не найдены'}
        return render(request, 'wallpapers_main\\viewIndexImage.html', context=context)
    preview_image = image_sources.filter(size='1280x720').get()
    context = {'preview_image':preview_image, 'image_sources':image_sources, 'image_name':image_name}
    return render(request, 'wallpapers_main\\viewIndexImage.html', context=context)

def view_image(request, category='all', page=1):
    if category=='all':
        context = get_all_images(page=page)
    else:
        context = get_image_by_category(category=category, page=page)
    return render(request, 'wallpapers_main\\viewImage.html', context=context)

def sort(request):
    try:
        image = Images.objects.filter(categories=None)[:1].get()
    except DoesNotExist:
        error_message = 'Все изображения отсортированы'
        error_redirect = 'images:recommend'
        return render(request, 'wallpapers_main:error',
                     context = {'error_message':error_message,
                                'error_redirect':error_redirect})
    else:
        image = Source.objects.filter(name = image).filter(size='1280x720').get()
    categories = Category.objects.all()
    return render(request, 'wallpapers_main\sort.html',
                  context = {'image':image,
                             'categories':categories})

def category_take(request):

    source = Source.objects.filter(source = request.POST.get('source')).get()
    image = source.name
    category = Category.objects.filter(category_link_name = request.POST.get('category'))
    image.categories.set(category)
    image.save()
    return HttpResponseRedirect(reverse('wallpapers_main:sort'))

def error_redirect(request):
    return HttpResponseRedirect(reverse(request.POST.get('error_redirect')))

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------

def get_all_images(page=1):
    '''return context with all category is exist and instace of Paginator, when contains all image is exist'''
    context={}
    IMAGES_ON_PAGE = 24
    all_category = Category.objects.all()
    images = Source.objects.filter(size='1280x720')
    paginator = Paginator(images, IMAGES_ON_PAGE)
    page_obj = paginator.get_page(page)
    context.update({'all_category':all_category, 'images':page_obj, 'page_name':'Все картинки', 'current_category':'all'})
    return context


def get_image_by_category(category, page=1):
    '''return context with all category is exist and instace of Paginator, when contains all image by category'''
    IMAGES_ON_PAGE = 24
    all_category = Category.objects.all()
    images = Source.objects.filter(name__categories__category_link_name=category).filter(size='1280x720')
    category_name = Category.objects.filter(category_link_name=category).get()
    page_name = category_name.category_name
    paginator = Paginator(images, IMAGES_ON_PAGE)
    page_obj = paginator.get_page(page)
    context = {'all_category': all_category,
               'images': page_obj,
               'page_name': page_name,
               'current_category': category,
               'is_content': True if page_obj else False,
               'is_paginate': True if paginator.count > 1 else False}
    return context


def parse_site_and_download(url, duration = 10): #Парсит сайт по url и загружает картинки со страниц от 0 до duration
    parser = Parser(url = url)
    print('Parsing...')
    images_dict = parser.parse(duration = duration)
    result = tuple()
    for image_name in images_dict:
        try:
            image = Images.objects.create(name = image_name)
        except IntegrityError:
            continue
        for image_source, image_size in images_dict[image_name].items():
            source = Source(name = image, size = image_size, source = image_source)
            source.save()
            result = result + ((image.name, source.size, source.source),)
    return result

templates/base_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'my.css' %}" type="text/css">
    <!-- <script src="bootstrap/js/bootstrap.js"></script> -->
  </head>
  <body>
    <div id="navpanel" class="conteiner navpanel">
      <div class="row ">
        <div class="col-auto">
          <div class="row navpanel-btn">
            <div class="col-auto ">
              <h2>
                <a href="{% url 'wallpapers_main:recommend' %}" class="navbuttom">Дом</a>
              </h2>
            </div>
            <div class="col-auto ">
              <h2>
                <a href="{% url 'wallpapers_main:sort' %}" class="navbuttom">Категоризировать</a>
              </h2>
            </div>
            <div class="col-auto ">
              <h2>
                <a href="{% url 'wallpapers_main:load' %}" class="navbuttom">Добавить</a>
              </h2>
            </div>
          </div>
        </div>
        <div class="col"></div>
        </div>
      </div>
    </div>

    <div id="content" class="row">
        {# Колонка для левого бара #}

        {% block left_bar %}
            <div id="side_bar_empty" class="col-2"></div>
        {% endblock %}

        <div id="content_conteiner" class="col-8">
            {% block content %}
            {% endblock%}
        </div>

        <div id="right_bar" class="col-2"></div>
    </div>
  </body>
</html>

templates/wallpapers_main/error.html
{% extends "base_template.html" %}

{% block title %}
Ошибка
{% endblock %}

{% block content %}
  <p>{{error_massage}}</p>
  <form action="{% url 'wallpapers_main:error_redirect'}" method="POST">
    <input type="text" name="link" value="{{error_redirect}}" hidden>
    <input type="submit" value="Продолжить">
  </form>
{% endblock %}

templates/wallpapers_main/load.html
{% extends "base_template.html" %}

{% block title %}
Загрузка картинки
{% endblock %}

{% block content %}

  <!-- <div name="upload_file" class="conteiner-fluid"> -->
    <!-- <h3>Загрузка с жесткого диска</h3>
    <form action="{% url 'wallpapers_main:load_result' %}" enctype="multipart/form-data" class="form-group" method="post">
      {%csrf_token%}
      <input name="name" type="text"  placeholder="Название" class="form-control">
      <input name="load_select" type="text" hidden value="upload_file">
      <select name="size" class="form-control" >
        <option selected>Разрешение</option>
        {% for size in sizes %}
        <option value = {{size}}>{{ size }}</option>
        {% endfor %}
      </select>
      <input name="file" type="file" class="form-control">
      <input type="submit" value="Загрузить" class="form-control">
    </form>
  </div> -->

  <div name="parse_site" class="conteiner-fluid">
    <h3>Загрузить с сайта wallpaperscraft.ru</h3>
    <form action="{% url 'wallpapers_main:load_result' %}" class="form-group" method="post">.
      {%csrf_token%}
      <input name="url" placeholder="Адрес раздела" type="text" class="form-control">
      <input name="load_select" type="text" hidden value="parse_site">
      <input name="duration" placeholder="Кол-во страниц" type="text" class="form-control">
      <input type="submit" value="Загрузить" class="form-control">
    </form>
  </div>

{% endblock%}

templates/wallpapers_main/result.html
{% extends "base_template.html" %}

{% block title %}
Результаты загрузки
{% endblock %}

{% block content %}
<div class="conteiner_fluid" name="results">
  <div class="row">
    <div class="col">Название</div>
    <div class="col">Размер</div>
    <div class="col">Источник</div>
  </div>

  {% for image in result %}
    <div class="row">
      {% for item in image %}
      <div class="col"><p>{{item}}</p></div>
      {%endfor%}
    </div>


  {%endfor%}
</div>

{% endblock%}

templates/wallpapers_main/sort.html
{% extends "base_template.html" %}

{% block title %}
Выбор категории
{% endblock %}

{% block content %}
  <div name=image class="conteiner">
    <img src="{{image.source}}" class="img-thumbnail">
  </div>

  <form name="category_choice" action="{% url 'wallpapers_main:category_take' %}" method="post">
    <div class="form-group">
      {% csrf_token %}
      <input name="source" type="text" hidden value="{{image}}">
      <select name="category" multiple class="form-control">
        {% for category in categories %}
        <option value="{{category.category_link_name}}">{{category.category_name}}</option>
        {% endfor %}
      </select>
      <!-- <button form="category_choice" type="submit" name="button" class="form-control">Принять</button> -->
      <input type="submit" value="Принять" class="form-control">
    </div>
  </form>
{% endblock %}

templates/wallpapers_main/viewImage.html
{% extends "base_template.html" %}

{% block title %}
{{page_name}}
{% endblock %}

{# Список картинок #}
{% block content %}
  <div class="col">
    <div name="images" class="row">
          {% if not is_content %}
              <p2>Картинки не найдены</p2>
          {% else %}
              {# Наполнение картинками #}
              {% for image in images %}
                  <div id="image_box" class="col-3">
                      <a href="{% url 'wallpapers_main:image_page' image.name %}">
                          <img src="{{image.source}}" class="img-fluid"></a>
                  </div>
              {% endfor %}
          {% endif %}
    </div>
    {% if is_paginate %}
    <div name="page_nav" class="raw">
        {% if images.has_previous %}
            <a href="{% url 'wallpapers_main:category_page' current_category images.previous_page_number %}">Назад</a>
        {% endif %}
            {{ images.number }}
        {% if images.has_next %}
            <a href="{% url 'wallpapers_main:category_page' current_category images.next_page_number %}">Вперед</a>
        {% endif %}
    </div>
    {% endif %}
  </div>
</div>
{% endblock%}

{#  Список категорий  #}
{% block left_bar %}
    <div id="side_bar_content" class="col-2">
        <div class="row">
            <div class="col btn-group-vertical">
                <a href="{% url 'wallpapers_main:category' category='all' %}" class="btn btn-primary">Все</a>
                {% for category in all_category %}
                    <a href="{% url 'wallpapers_main:category' category.category_link_name %}" class="btn btn-primary">{{category.category_name}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/wallpapers_main/viewIndexImage.html
{% extends "base_template.html" %}

{% block title %}
{{image_name}}
{% endblock %}

{% block content %}
<img src="{{preview_image.source}}" class="img-thumbnail"><br>
<span>
  Выберите разрешение: 
  {% for image_source in image_sources %}
    <a href="{{image_source.source}}">{{image_source.size}}</a>
  {% endfor %}
</span>

{% endblock%}